### ISSUE TITLE
Investigate the best way to circumvent reading the .gitattributes per check/fliter

### ISSUE THREAD

**Issue by cjhoward92** [Axosoft/nodegit-lfs#3]
Find a way to determine if the current .gitattributes files has changed so we potentially only have to read it one time per repo, and will be notified if something changes. We could look at using the index and any caches it may have to determine if the file has changed.

**Comment by cjhoward92** [comment]
@jgrosso I am interested in your opinion on this. The `check.js` file reads the `.gitattributes` each time we check a file. You can imagine this incurs some overhead. An obvious improvement is to avoid this. Not sure how to best cache the filters, though. Needs to change per repo and needs to change when the file changes. I think the check callback gets the repo instance but I need to verify. I know smudge and clean do.

**Comment by jgrosso** [comment]
Re: watching `.gitattributes` for changes, would https://github.com/Axosoft/nsfw work?
Whenever that changes, we could parse out the filters and store them wherever. (Whenever a repo changes, we'd setup a listener on the new `.gitattributes` file and go from there).
Would this serve our needs, do you think?

**Comment by cjhoward92** [comment]
Yeah nsfw could work. We will check it out. Not sure the overhead of adding in nsfw. It feels a bit weird for a NodeGit augmentation library to spawn an nsfw instance.

**Comment by cjhoward92** [comment]
Updated to use `NodeGit.Attr.get`
